name: MinecartLauncher
main: com.nickeddy.MinecartLauncher.MinecartLauncher
version: .1
commands:
    launch:
        description: Launches a minecart with the player in it going the direction they are facing.
        usage: /<command>
permissions:
    nickeddy.MinecartLauncher.launch:
        description: Whether or not a player can launch a minecart.
        default: true
